### ISSUE TITLE
压测出现 failed: connection reset by peer

### ISSUE THREAD

**Issue by JellyZero** [cloudwego/hertz-benchmark#5]

**Comment by li-jin-gou** [comment]
@JellyZero  Hello 
- 给出的信息比较简洁，可以参考一下 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
- 这种情况建议给出稍微详细的上下文信息，否则不太好分析问题 :disappointed:

**Comment by Skyenought** [comment]
> _No description provided._

希望你可以仔细描述一下问题，有助于尽快得到解决方案

**Comment by JellyZero** [comment]
就./scripts/benchmark_wrk.sh 这个命令，每次都是hertz报错

![image](https://user-images.githubusercontent.com/109566229/187968411-24149921-b70b-4d46-a6a4-e5d34690fccd.png)

**Comment by welkeyever** [comment]
这个是client对端测试完毕后通过reset方式关连接导致的，忽略就行；这个错误标准库应该是直接吞掉了，不过[netpoll](https://github.com/cloudwego/netpoll)应该是主动打印的
