### ISSUE TITLE
压测脚本设置请求量与实际client向server发送的请求量不符

### ISSUE THREAD

**Issue by edufriendchen** [cloudwego/hertz-benchmark#6]
**Describe the bug**

在使用项目目录下./scripts/benchmark_client.sh 或者 ./scripts/benchmark_server.sh 压测脚本启动client对server压测时，**发现脚本中参数n（表示请求总量）与实际client向server发送的请求量不符**。分析源码后发现项目目录下./runner/main.go文件第81行设置了一个100*1000的默认预热请求量，但在日志中却没有将这十万的请求量算入。请官方核实并更正这个小细节，错误截图如下。

**Screenshots**
运行脚本 total-50,000
![xshell](https://user-images.githubusercontent.com/78396698/196598912-895874cc-6103-4507-bb4a-56a81a1b90e6.jpg)
实际请求 total-150,000
![actual](https://user-images.githubusercontent.com/78396698/196599690-4b6ef386-3683-48ab-bfb5-c51d0785ed5d.png)

除了这个小细节外，项目README.md文档有一点描述不恰当：
![inaccurate](https://user-images.githubusercontent.com/78396698/196601162-ac3f1a12-ff27-4671-9eb5-080492997b37.png)
./scripts/env.sh中并没有参数n，n应该在压测脚本中

如有误解，请谅解！本人邮箱： 545498529@qq.com

**Comment by li-jin-gou** [comment]
我们看下，感谢反馈 @EduFriendChen  :heart:

**Comment by edufriendchen** [comment]
> 我们看下，感谢反馈 @EduFriendChen ❤️

好的，个人感觉。不知道对不对。还望不吝赐教！

**Comment by Duslia** [comment]
预热不应该算在 total 中的，这个没啥问题。

**Comment by Duslia** [comment]
README 中的 n 的话我改下

**Comment by edufriendchen** [comment]
> 预热不应该算在 total 中的，这个没啥问题。

OK 。 我一开始怎么看请求量都不对，后来server里打点，才看到预热的请求都打到server服务了。这里我注意一下。

**Comment by welkeyever** [comment]
感谢反馈，感兴趣的话可以加入hertz的飞书用户群，一起交流哈~ @EduFriendChen

**Comment by welkeyever** [comment]
fyi~
![飞书20221019-134858](https://user-images.githubusercontent.com/9826697/196607502-11792789-fdb9-42aa-90be-6251f4df9767.png)

**Comment by edufriendchen** [comment]
> 感谢反馈，感兴趣的话可以加入hertz的飞书用户群，一起交流哈~ @EduFriendChen

进了，飞书字节校园忠实学生。最近在弄字节校园的镜像计划项目实战，有意向加入咱们大家庭。

**Comment by welkeyever** [comment]
> > 感谢反馈，感兴趣的话可以加入hertz的飞书用户群，一起交流哈~ @EduFriendChen
> 
> 进了，飞书字节校园忠实学生。最近在弄字节校园的镜像计划项目实战，有意向加入咱们大家庭。

如果对hertz相关的开发建设感兴趣也可以参与进来~目前社区commiter申请也是open的🤗

**Comment by edufriendchen** [comment]
> > > 感谢反馈，感兴趣的话可以加入hertz的飞书用户群，一起交流哈~ @EduFriendChen
> > 
> > 
> > 进了，飞书字节校园忠实学生。最近在弄字节校园的镜像计划项目实战，有意向加入咱们大家庭。
> 
> 如果对hertz相关的开发建设感兴趣也可以参与进来~目前社区commiter申请也是open的🤗

我可以申请吗，感觉很荣幸。

**Comment by li-jin-gou** [comment]
> > > > 感谢反馈，感兴趣的话可以加入hertz的飞书用户群，一起交流哈~ @EduFriendChen
> > > 
> > > 
> > > 进了，飞书字节校园忠实学生。最近在弄字节校园的镜像计划项目实战，有意向加入咱们大家庭。
> > 
> > 
> > 如果对hertz相关的开发建设感兴趣也可以参与进来~目前社区commiter申请也是open的🤗
> 
> 我可以申请吗，感觉很荣幸。

refer to https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#community-membership
